name: CI/CD to Azure Web App (Code)

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  APP_NAME: clencyfront
  ARTIFACT_DIR: dist

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: cd ${{ env.ARTIFACT_DIR }} && zip -r ../site.zip .
      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: site.zip
          retention-days: 7

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: site
      - run: unzip -o site.zip -d site
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./site
